default_platform(:ios)

platform :ios do
  desc "Run both unit and ui tests"
  lane :"test" do
    run_tests(
      project: "LiquorShop.xcodeproj",
      xcargs: "-testPlan all-test",
      only_test_configurations: ['Configuration 1'],
      clean: true
    )
  end

  desc "Run unit tests only"
  lane :"unit-test" do
    run_tests(
      project: "LiquorShop.xcodeproj",
      xcargs: "-testPlan unit-test",
      only_test_configurations: ['Configuration 1'],
      clean: true
    )
  end

  desc "Run UI tests only"
  lane :"ui-test" do
    run_tests(
      project: "LiquorShop.xcodeproj",
      xcargs: "-testPlan ui-test",
      only_test_configurations: ['Configuration 1'],
      clean: true
    )
  end

  desc "Organises the files and directory structure alphabetically"
  lane :"organise" do
    sh ("cd .. && bundle exec synx LiquorShop.xcodeproj")
  end

end